#!/usr/bin/env python

Import("env")
Import("env_modules")

module_env = env.Clone()

module_env.Append(CPPDEFINES=["SAND_SLIDE"])

module_env.add_source_files(env.modules_sources, "*.cpp")
module_env.add_source_files(env.modules_sources, "elements/chemical/*.cpp")
module_env.add_source_files(env.modules_sources, "elements/life/*.cpp")
module_env.add_source_files(env.modules_sources, "elements/space/*.cpp")
module_env.add_source_files(env.modules_sources, "elements/basic/*.cpp")
module_env.add_source_files(env.modules_sources, "elements/build/*.cpp")
